# Generated by Django 3.2.5 on 2021-07-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArpScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, verbose_name='IP Address')),
                ('mac', models.CharField(max_length=60, verbose_name='MAC Address')),
                ('host', models.CharField(max_length=50, verbose_name='HostName')),
                ('domain', models.CharField(max_length=100, verbose_name='Domain Name')),
                ('os', models.CharField(max_length=20, verbose_name='Operating System')),
            ],
        ),
    ]
